// src/lib/types.ts
export enum SyncJobType {
  QUICKBOOKS_INVOICES = 'QUICKBOOKS_INVOICES',
  QUICKBOOKS_ACCOUNTS = 'QUICKBOOKS_ACCOUNTS',
  QUICKBOOKS_CREDIT_NOTES = 'QUICKBOOKS_CREDIT_NOTES',
  QUICKBOOKS_JOURNAL_ENTRIES = 'QUICKBOOKS_JOURNAL_ENTRIES',
  QUICKBOOKS_PAYMENTS = 'QUICKBOOKS_PAYMENTS',
  QUICKBOOKS_TRANSACTIONS = 'QUICKBOOKS_TRANSACTIONS',
  QUICKBOOKS_VENDOR_CREDITS = 'QUICKBOOKS_VENDOR_CREDITS',
  PLAID_BANK_ACCOUNTS = 'PLAID_BANK_ACCOUNTS',
  PLAID_TRANSACTIONS = 'PLAID_TRANSACTIONS',
}

export interface SyncJobRun {
  id: string;
  status: string;
  startedAt?: string;
  finishedAt?: string;
}